# Generated by Django 3.2.7 on 2021-09-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/defaulprofile.jpg', upload_to=''),
        ),
    ]
