# Generated by Django 3.2.7 on 2021-09-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defaulprofile.jpg', upload_to=''),
        ),
    ]
