# Generated by Django 3.2.7 on 2021-09-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
